export type AsmaName = {
  id: number;
  arabic: string;
  transliteration: string;
  meaning: string;
  /** Audio filename (without .mp3) for IslamicAPI CDN */
  audio: string;
};

const ASMA_AUDIO_BASE = 'https://islamicapi.com/audio/asma-ul-husna';

export function getAsmaAudioUrl(audioFilename: string): string {
  return `${ASMA_AUDIO_BASE}/${audioFilename}.mp3`;
}

/** Audio filenames from IslamicAPI (https://islamicapi.com/audio/asma-ul-husna/) */
const ASMA_AUDIO_FILES: Record<number, string> = {
  1: 'rahman', 2: 'rahim', 3: 'malik', 4: 'quddus', 5: 'salam', 6: 'mumin', 7: 'muhaimin',
  8: 'aziz', 9: 'jabbar', 10: 'mutakabbir', 11: 'khaliq', 12: 'bari', 13: 'musawwir',
  14: 'ghaffar', 15: 'qahhar', 16: 'wahhab', 17: 'razzaq', 18: 'fattah', 19: 'alim',
  20: 'qabid', 21: 'basit', 22: 'khafid', 23: 'rafi', 24: 'muizz', 25: 'mudhill',
  26: 'sami', 27: 'basir', 28: 'hakam', 29: 'adl', 30: 'latif', 31: 'khabir',
  32: 'halim', 33: 'azim', 34: 'ghafur', 35: 'shakur', 36: 'ali', 37: 'kabir',
  38: 'hafiz', 39: 'muqit', 40: 'hasib', 41: 'jalil', 42: 'karim', 43: 'raqib',
  44: 'mujib', 45: 'wasi', 46: 'hakim', 47: 'wadud', 48: 'majeed', 49: 'baith',
  50: 'shahid', 51: 'haqq', 52: 'wakil', 53: 'qawi', 54: 'matin', 55: 'waliy',
  56: 'hamid', 57: 'muhsi', 58: 'mubdi', 59: 'muid', 60: 'muhyi', 61: 'mumit',
  62: 'hayy', 63: 'qayyum', 64: 'wajid', 65: 'majid', 66: 'wahid', 67: 'ahad',
  68: 'samad', 69: 'qadir', 70: 'muqtadir', 71: 'muqaddim', 72: 'muakhkhir',
  73: 'awwal', 74: 'akhir', 75: 'zahir', 76: 'batin', 77: 'wali', 78: 'muta_ali',
  79: 'barr', 80: 'tawwab', 81: 'muntaqim', 82: 'afuw', 83: 'rauf',
  84: 'malik_ul_mulk', 85: 'dhu_l_jalali_wal_ikram', 86: 'muqsit', 87: 'jami',
  88: 'ghaniy', 89: 'mughni', 90: 'mani', 91: 'darr', 92: 'nafi', 93: 'nur',
  94: 'hadi', 95: 'badi', 96: 'baqi', 97: 'warith', 98: 'rashid', 99: 'sabur',
};

export const ASMA_UL_HUSNA: AsmaName[] = [
  { id: 1, arabic: 'ٱلرَّحْمَٰنُ', transliteration: 'Ar-Rahman', meaning: 'The Most Merciful', audio: ASMA_AUDIO_FILES[1]! },
  { id: 2, arabic: 'ٱلرَّحِيمُ', transliteration: 'Ar-Rahim', meaning: 'The Especially Merciful', audio: ASMA_AUDIO_FILES[2]! },
  { id: 3, arabic: 'ٱلْمَلِكُ', transliteration: 'Al-Malik', meaning: 'The King, Owner of Dominion', audio: ASMA_AUDIO_FILES[3]! },
  { id: 4, arabic: 'ٱلْقُدُّوسُ', transliteration: 'Al-Quddus', meaning: 'The Absolutely Pure', audio: ASMA_AUDIO_FILES[4]! },
  { id: 5, arabic: 'ٱلسَّلَامُ', transliteration: 'As-Salam', meaning: 'The Source of Peace', audio: ASMA_AUDIO_FILES[5]! },
  { id: 6, arabic: 'ٱلْمُؤْمِنُ', transliteration: "Al-Mu'min", meaning: 'The Granter of Security and Faith', audio: ASMA_AUDIO_FILES[6]! },
  { id: 7, arabic: 'ٱلْمُهَيْمِنُ', transliteration: 'Al-Muhaymin', meaning: 'The Guardian, The Overseer', audio: ASMA_AUDIO_FILES[7]! },
  { id: 8, arabic: 'ٱلْعَزِيزُ', transliteration: "Al-'Aziz", meaning: 'The Almighty, The Invincible', audio: ASMA_AUDIO_FILES[8]! },
  { id: 9, arabic: 'ٱلْجَبَّارُ', transliteration: 'Al-Jabbar', meaning: 'The Compeller, The Restorer', audio: ASMA_AUDIO_FILES[9]! },
  { id: 10, arabic: 'ٱلْمُتَكَبِّرُ', transliteration: 'Al-Mutakabbir', meaning: 'The Supreme, The Majestic', audio: ASMA_AUDIO_FILES[10]! },
  { id: 11, arabic: 'ٱلْخَٰلِقُ', transliteration: 'Al-Khaliq', meaning: 'The Creator, The Maker', audio: ASMA_AUDIO_FILES[11]! },
  { id: 12, arabic: 'ٱلْبَارِئُ', transliteration: "Al-Bari'", meaning: 'The Originator, The Inventor', audio: ASMA_AUDIO_FILES[12]! },
  { id: 13, arabic: 'ٱلْمُصَوِّرُ', transliteration: 'Al-Musawwir', meaning: 'The Fashioner', audio: ASMA_AUDIO_FILES[13]! },
  { id: 14, arabic: 'ٱلْغَفَّارُ', transliteration: 'Al-Ghaffar', meaning: 'The Great Forgiver', audio: ASMA_AUDIO_FILES[14]! },
  { id: 15, arabic: 'ٱلْقَهَّارُ', transliteration: 'Al-Qahhar', meaning: 'The Subduer', audio: ASMA_AUDIO_FILES[15]! },
  { id: 16, arabic: 'ٱلْوَهَّابُ', transliteration: 'Al-Wahhab', meaning: 'The Giver of Gifts', audio: ASMA_AUDIO_FILES[16]! },
  { id: 17, arabic: 'ٱلرَّزَّاقُ', transliteration: 'Ar-Razzaq', meaning: 'The Ever-Providing', audio: ASMA_AUDIO_FILES[17]! },
  { id: 18, arabic: 'ٱلْفَتَّاحُ', transliteration: 'Al-Fattah', meaning: 'The Opener, The Judge', audio: ASMA_AUDIO_FILES[18]! },
  { id: 19, arabic: 'ٱلْعَلِيمُ', transliteration: "Al-'Alim", meaning: 'The All-Knowing', audio: ASMA_AUDIO_FILES[19]! },
  { id: 20, arabic: 'ٱلْقَابِضُ', transliteration: 'Al-Qabid', meaning: 'The Withholder', audio: ASMA_AUDIO_FILES[20]! },
  { id: 21, arabic: 'ٱلْبَاسِطُ', transliteration: 'Al-Basit', meaning: 'The Expander', audio: ASMA_AUDIO_FILES[21]! },
  { id: 22, arabic: 'ٱلْخَافِضُ', transliteration: 'Al-Khafid', meaning: 'The Reducer', audio: ASMA_AUDIO_FILES[22]! },
  { id: 23, arabic: 'ٱلرَّافِعُ', transliteration: "Ar-Rafi'", meaning: 'The Exalter', audio: ASMA_AUDIO_FILES[23]! },
  { id: 24, arabic: 'ٱلْمُعِزُّ', transliteration: "Al-Mu'izz", meaning: 'The Giver of Honor', audio: ASMA_AUDIO_FILES[24]! },
  { id: 25, arabic: 'ٱلْمُذِلُّ', transliteration: 'Al-Mudhill', meaning: 'The Humiliator', audio: ASMA_AUDIO_FILES[25]! },
  { id: 26, arabic: 'ٱلسَّمِيعُ', transliteration: "As-Sami'", meaning: 'The All-Hearing', audio: ASMA_AUDIO_FILES[26]! },
  { id: 27, arabic: 'ٱلْبَصِيرُ', transliteration: 'Al-Basir', meaning: 'The All-Seeing', audio: ASMA_AUDIO_FILES[27]! },
  { id: 28, arabic: 'ٱلْحَكَمُ', transliteration: 'Al-Hakam', meaning: 'The Judge', audio: ASMA_AUDIO_FILES[28]! },
  { id: 29, arabic: 'ٱلْعَدْلُ', transliteration: "Al-'Adl", meaning: 'The Utterly Just', audio: ASMA_AUDIO_FILES[29]! },
  { id: 30, arabic: 'ٱللَّطِيفُ', transliteration: 'Al-Latif', meaning: 'The Gentle, The Subtle', audio: ASMA_AUDIO_FILES[30]! },
  { id: 31, arabic: 'ٱلْخَبِيرُ', transliteration: 'Al-Khabir', meaning: 'The All-Aware', audio: ASMA_AUDIO_FILES[31]! },
  { id: 32, arabic: 'ٱلْحَلِيمُ', transliteration: 'Al-Halim', meaning: 'The Forbearing', audio: ASMA_AUDIO_FILES[32]! },
  { id: 33, arabic: 'ٱلْعَظِيمُ', transliteration: "Al-'Azim", meaning: 'The Magnificent', audio: ASMA_AUDIO_FILES[33]! },
  { id: 34, arabic: 'ٱلْغَفُورُ', transliteration: 'Al-Ghafur', meaning: 'The Forgiving', audio: ASMA_AUDIO_FILES[34]! },
  { id: 35, arabic: 'ٱلشَّكُورُ', transliteration: 'Ash-Shakur', meaning: 'The Most Appreciative', audio: ASMA_AUDIO_FILES[35]! },
  { id: 36, arabic: 'ٱلْعَلِيُّ', transliteration: "Al-'Ali", meaning: 'The Most High', audio: ASMA_AUDIO_FILES[36]! },
  { id: 37, arabic: 'ٱلْكَبِيرُ', transliteration: 'Al-Kabir', meaning: 'The Greatest', audio: ASMA_AUDIO_FILES[37]! },
  { id: 38, arabic: 'ٱلْحَفِيظُ', transliteration: 'Al-Hafiz', meaning: 'The Preserver', audio: ASMA_AUDIO_FILES[38]! },
  { id: 39, arabic: 'ٱلْمُقِيتُ', transliteration: 'Al-Muqit', meaning: 'The Sustainer', audio: ASMA_AUDIO_FILES[39]! },
  { id: 40, arabic: 'ٱلْحَسِيبُ', transliteration: 'Al-Hasib', meaning: 'The Reckoner', audio: ASMA_AUDIO_FILES[40]! },
  { id: 41, arabic: 'ٱلْجَلِيلُ', transliteration: 'Al-Jalil', meaning: 'The Majestic', audio: ASMA_AUDIO_FILES[41]! },
  { id: 42, arabic: 'ٱلْكَرِيمُ', transliteration: 'Al-Karim', meaning: 'The Most Generous', audio: ASMA_AUDIO_FILES[42]! },
  { id: 43, arabic: 'ٱلرَّقِيبُ', transliteration: 'Ar-Raqib', meaning: 'The Watchful', audio: ASMA_AUDIO_FILES[43]! },
  { id: 44, arabic: 'ٱلْمُجِيبُ', transliteration: 'Al-Mujib', meaning: 'The Responsive', audio: ASMA_AUDIO_FILES[44]! },
  { id: 45, arabic: 'ٱلْوَاسِعُ', transliteration: "Al-Wasi'", meaning: 'The All-Encompassing', audio: ASMA_AUDIO_FILES[45]! },
  { id: 46, arabic: 'ٱلْحَكِيمُ', transliteration: 'Al-Hakim', meaning: 'The All-Wise', audio: ASMA_AUDIO_FILES[46]! },
  { id: 47, arabic: 'ٱلْوَدُودُ', transliteration: 'Al-Wadud', meaning: 'The Most Loving', audio: ASMA_AUDIO_FILES[47]! },
  { id: 48, arabic: 'ٱلْمَجِيدُ', transliteration: 'Al-Majid', meaning: 'The Glorious', audio: ASMA_AUDIO_FILES[48]! },
  { id: 49, arabic: 'ٱلْبَاعِثُ', transliteration: "Al-Ba'ith", meaning: 'The Resurrector', audio: ASMA_AUDIO_FILES[49]! },
  { id: 50, arabic: 'ٱلشَّهِيدُ', transliteration: 'Ash-Shahid', meaning: 'The Witness', audio: ASMA_AUDIO_FILES[50]! },
  { id: 51, arabic: 'ٱلْحَقُّ', transliteration: 'Al-Haqq', meaning: 'The Absolute Truth', audio: ASMA_AUDIO_FILES[51]! },
  { id: 52, arabic: 'ٱلْوَكِيلُ', transliteration: 'Al-Wakil', meaning: 'The Trustee', audio: ASMA_AUDIO_FILES[52]! },
  { id: 53, arabic: 'ٱلْقَوِيُّ', transliteration: 'Al-Qawiyy', meaning: 'The All-Strong', audio: ASMA_AUDIO_FILES[53]! },
  { id: 54, arabic: 'ٱلْمَتِينُ', transliteration: 'Al-Matin', meaning: 'The Firm, The Steadfast', audio: ASMA_AUDIO_FILES[54]! },
  { id: 55, arabic: 'ٱلْوَلِيُّ', transliteration: 'Al-Waliyy', meaning: 'The Protector', audio: ASMA_AUDIO_FILES[55]! },
  { id: 56, arabic: 'ٱلْحَمِيدُ', transliteration: 'Al-Hamid', meaning: 'The Praiseworthy', audio: ASMA_AUDIO_FILES[56]! },
  { id: 57, arabic: 'ٱلْمُحْصِي', transliteration: 'Al-Muhsi', meaning: 'The All-Enumerating', audio: ASMA_AUDIO_FILES[57]! },
  { id: 58, arabic: 'ٱلْمُبْدِئُ', transliteration: "Al-Mubdi'", meaning: 'The Originator', audio: ASMA_AUDIO_FILES[58]! },
  { id: 59, arabic: 'ٱلْمُعِيدُ', transliteration: "Al-Mu'id", meaning: 'The Restorer', audio: ASMA_AUDIO_FILES[59]! },
  { id: 60, arabic: 'ٱلْمُحْيِي', transliteration: 'Al-Muhyi', meaning: 'The Giver of Life', audio: ASMA_AUDIO_FILES[60]! },
  { id: 61, arabic: 'ٱلْمُمِيتُ', transliteration: 'Al-Mumit', meaning: 'The Creator of Death', audio: ASMA_AUDIO_FILES[61]! },
  { id: 62, arabic: 'ٱلْحَيُّ', transliteration: 'Al-Hayy', meaning: 'The Ever-Living', audio: ASMA_AUDIO_FILES[62]! },
  { id: 63, arabic: 'ٱلْقَيُّومُ', transliteration: 'Al-Qayyum', meaning: 'The Sustainer', audio: ASMA_AUDIO_FILES[63]! },
  { id: 64, arabic: 'ٱلْوَاجِدُ', transliteration: 'Al-Wajid', meaning: 'The Finder', audio: ASMA_AUDIO_FILES[64]! },
  { id: 65, arabic: 'ٱلْمَاجِدُ', transliteration: 'Al-Majid', meaning: 'The Illustrious', audio: ASMA_AUDIO_FILES[65]! },
  { id: 66, arabic: 'ٱلْوَاحِدُ', transliteration: 'Al-Wahid', meaning: 'The One', audio: ASMA_AUDIO_FILES[66]! },
  { id: 67, arabic: 'ٱلْأَحَدُ', transliteration: 'Al-Ahad', meaning: 'The Unique', audio: ASMA_AUDIO_FILES[67]! },
  { id: 68, arabic: 'ٱلصَّمَدُ', transliteration: 'As-Samad', meaning: 'The Eternal Refuge', audio: ASMA_AUDIO_FILES[68]! },
  { id: 69, arabic: 'ٱلْقَادِرُ', transliteration: 'Al-Qadir', meaning: 'The All-Able', audio: ASMA_AUDIO_FILES[69]! },
  { id: 70, arabic: 'ٱلْمُقْتَدِرُ', transliteration: 'Al-Muqtadir', meaning: 'The All-Powerful', audio: ASMA_AUDIO_FILES[70]! },
  { id: 71, arabic: 'ٱلْمُقَدِّمُ', transliteration: 'Al-Muqaddim', meaning: 'The Expediter', audio: ASMA_AUDIO_FILES[71]! },
  { id: 72, arabic: 'ٱلْمُؤَخِّرُ', transliteration: "Al-Mu'akhkhir", meaning: 'The Delayer', audio: ASMA_AUDIO_FILES[72]! },
  { id: 73, arabic: 'ٱلْأَوَّلُ', transliteration: 'Al-Awwal', meaning: 'The First', audio: ASMA_AUDIO_FILES[73]! },
  { id: 74, arabic: 'ٱلْآخِرُ', transliteration: 'Al-Akhir', meaning: 'The Last', audio: ASMA_AUDIO_FILES[74]! },
  { id: 75, arabic: 'ٱلظَّاهِرُ', transliteration: 'Az-Zahir', meaning: 'The Manifest', audio: ASMA_AUDIO_FILES[75]! },
  { id: 76, arabic: 'ٱلْبَاطِنُ', transliteration: 'Al-Batin', meaning: 'The Hidden', audio: ASMA_AUDIO_FILES[76]! },
  { id: 77, arabic: 'ٱلْوَالِي', transliteration: 'Al-Wali', meaning: 'The Sole Governor', audio: ASMA_AUDIO_FILES[77]! },
  { id: 78, arabic: 'ٱلْمُتَعَالِي', transliteration: "Al-Muta'ali", meaning: 'The Self-Exalted', audio: ASMA_AUDIO_FILES[78]! },
  { id: 79, arabic: 'ٱلْبَرُّ', transliteration: 'Al-Barr', meaning: 'The Source of All Goodness', audio: ASMA_AUDIO_FILES[79]! },
  { id: 80, arabic: 'ٱلتَّوَابُ', transliteration: 'At-Tawwab', meaning: 'The Ever-Pardoning', audio: ASMA_AUDIO_FILES[80]! },
  { id: 81, arabic: 'ٱلْمُنْتَقِمُ', transliteration: 'Al-Muntaqim', meaning: 'The Avenger', audio: ASMA_AUDIO_FILES[81]! },
  { id: 82, arabic: 'ٱلْعَفُوُّ', transliteration: "Al-'Afuww", meaning: 'The Pardoner', audio: ASMA_AUDIO_FILES[82]! },
  { id: 83, arabic: 'ٱلرَّءُوفُ', transliteration: "Ar-Ra'uf", meaning: 'The Most Kind', audio: ASMA_AUDIO_FILES[83]! },
  { id: 84, arabic: 'مَالِكُ ٱلْمُلْكِ', transliteration: 'Malik al-Mulk', meaning: 'Master of the Dominion', audio: ASMA_AUDIO_FILES[84]! },
  { id: 85, arabic: 'ذُو ٱلْجَلَالِ وَٱلْإِكْرَامِ', transliteration: 'Dhu al-Jalal wa al-Ikram', meaning: 'Possessor of Glory and Honor', audio: ASMA_AUDIO_FILES[85]! },
  { id: 86, arabic: 'ٱلْمُقْسِطُ', transliteration: 'Al-Muqsit', meaning: 'The Just One', audio: ASMA_AUDIO_FILES[86]! },
  { id: 87, arabic: 'ٱلْجَامِعُ', transliteration: "Al-Jami'", meaning: 'The Gatherer', audio: ASMA_AUDIO_FILES[87]! },
  { id: 88, arabic: 'ٱلْغَنِيُّ', transliteration: 'Al-Ghaniyy', meaning: 'The Self-Sufficient', audio: ASMA_AUDIO_FILES[88]! },
  { id: 89, arabic: 'ٱلْمُغْنِيُ', transliteration: 'Al-Mughni', meaning: 'The Enricher', audio: ASMA_AUDIO_FILES[89]! },
  { id: 90, arabic: 'ٱلْمَانِعُ', transliteration: "Al-Mani'", meaning: 'The Withholder', audio: ASMA_AUDIO_FILES[90]! },
  { id: 91, arabic: 'ٱلضَّارُّ', transliteration: 'Ad-Darr', meaning: 'The Distresser', audio: ASMA_AUDIO_FILES[91]! },
  { id: 92, arabic: 'ٱلنَّافِعُ', transliteration: "An-Nafi'", meaning: 'The Benefactor', audio: ASMA_AUDIO_FILES[92]! },
  { id: 93, arabic: 'ٱلنُّورُ', transliteration: 'An-Nur', meaning: 'The Light', audio: ASMA_AUDIO_FILES[93]! },
  { id: 94, arabic: 'ٱلْهَادِي', transliteration: 'Al-Hadi', meaning: 'The Guide', audio: ASMA_AUDIO_FILES[94]! },
  { id: 95, arabic: 'ٱلْبَدِيعُ', transliteration: "Al-Badi'", meaning: 'The Incomparable Originator', audio: ASMA_AUDIO_FILES[95]! },
  { id: 96, arabic: 'ٱلْبَاقِي', transliteration: 'Al-Baqi', meaning: 'The Ever-Lasting', audio: ASMA_AUDIO_FILES[96]! },
  { id: 97, arabic: 'ٱلْوَارِثُ', transliteration: 'Al-Warith', meaning: 'The Inheritor', audio: ASMA_AUDIO_FILES[97]! },
  { id: 98, arabic: 'ٱلرَّشِيدُ', transliteration: 'Ar-Rashid', meaning: 'The Guide to the Right Path', audio: ASMA_AUDIO_FILES[98]! },
  { id: 99, arabic: 'ٱلصَّبُورُ', transliteration: 'As-Sabur', meaning: 'The Patient', audio: ASMA_AUDIO_FILES[99]! },
];
